name: Make file

on:
  push:
    branches:
      - main

jobs:
  make-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run script
        run: bash makefile.sh
      - name: commit and push files
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add .
          git commit -m "make log" -a
          git push origin main