name: Git log

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  git-log:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: git setup
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "action@github.com"
      - name: log
        run: |
          git log --name-only --pretty=format:"commit %h: %s" -1 > log.txt
      - name: output
        run: cat log.txt
      - name: cleanup
        run: rm log.txt
